In [6]:
import numpy as np

In [10]:
a1 = np.array([1,2,3,4,5])
print(a1)
print(a1.shape)
print(a1.ndim)
print(a1.size)

[1 2 3 4 5]
(5,)
1
5


shape → dimensions


ndim → number of dimensions


size → total number of elements


dtype → datatype

In [18]:
a2 = np.array([  
    [1,2,3],
    [4,5,6]
])
print(a2)
print(a2.ndim)
print(a2.size)
print(a2.shape)

[[1 2 3]
 [4 5 6]]
2
6
(2, 3)


# Reshape : 
reshape cannot change the number of elements. , instead it changes the array shape into any dimension

In [23]:
# get array from 1 to 26
a = np.arange(1, 26)
print(a)

print(a.reshape(5,5))
# convert that array into 5x5

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


# Slicing :
removing a specifc part of the array 


In [ ]:
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

print(a[2,2])

print(a[0])

print(a[0:2]) 

print(a[: , 0]) # get col into row

print("----------------")
print(a[0:3,1:2]) # rows from 0th to 3rd and col 1st to 2nd

11
[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]
[ 1  5  9 13]
----------------
[[ 2]
 [ 6]
 [10]]


In [40]:
a = np.array([10, 20, 30])
b = np.array([2, 4, 5])

print(a @ b)
print(a*b)

250
[ 20  80 150]


# Statistics 

In [41]:
a = np.array([10, 20, 30, 40, 50])

print(np.mean(a))
print(np.median(a))
print(np.var(a))
print(np.std(a))

30.0
30.0
200.0
14.142135623730951


# Random numbers

In [51]:
np.random.rand(2,5)

array([[0.22869909, 0.19842657, 0.26599605, 0.40024628, 0.54640801],
       [0.56108883, 0.37509966, 0.94104301, 0.60892883, 0.1280849 ]])